// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFz9rs9qTP3S1LB9Gcj78uFkB6WzD-pxY',
    appId: '1:50333376086:web:c278c435fdd84980dd65f7',
    messagingSenderId: '50333376086',
    projectId: 'dalel-975d6',
    authDomain: 'dalel-975d6.firebaseapp.com',
    storageBucket: 'dalel-975d6.appspot.com',
    measurementId: 'G-W96K94H55J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZiZcTPAgG8WYh0Wyh53XaH-S6jc1x_Ic',
    appId: '1:50333376086:android:c4d054ea52321d7add65f7',
    messagingSenderId: '50333376086',
    projectId: 'dalel-975d6',
    storageBucket: 'dalel-975d6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoFXO-NLbB-2gJ5WXfvOI2eS6bySGyhPo',
    appId: '1:50333376086:ios:eb2fee8278b7bbd7dd65f7',
    messagingSenderId: '50333376086',
    projectId: 'dalel-975d6',
    storageBucket: 'dalel-975d6.appspot.com',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCoFXO-NLbB-2gJ5WXfvOI2eS6bySGyhPo',
    appId: '1:50333376086:ios:8733e2caf84c221bdd65f7',
    messagingSenderId: '50333376086',
    projectId: 'dalel-975d6',
    storageBucket: 'dalel-975d6.appspot.com',
    iosBundleId: 'com.example.dalel.RunnerTests',
  );
}
